### ISSUE TITLE
Erro de segurança

### ISSUE THREAD

**Issue by operfildoluiz** [ThalesRod/simulador-investimentos#1]
Fala, @ThalesRod!

Primeiro, parabéns pelo projeto =)

Ao usar a ferramenta, aparece a seguinte mensagem: ```Parece que algo deu errado! Por favor, simule novamente.```

Debugando no console, o erro é causado pois o projeto consome recursos http enquanto está hospedado em ambiente seguro (https)

```
jquery-3.3.1.min.js:2
Mixed Content: The page at 'https://thalesrod.github.io/simulador-investimentos/' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://api.mathjs.org/v4/'. This request has been blocked; the content must be served over HTTPS.
```

**Comment by ThalesRod** [comment]
Opa, @lhcgoncalves !

Obrigado por usar a ferramenta!

A API que a aplicação consome para realizar os cálculos relacionados à simulação somente dispõe o protocolo HTTP, e não o HTTPS.

Estou procurando alguma API alternativa para solucionar esse erro.

Edit: Problema resolvido! A API do math.js agora suporta https.
